### ISSUE TITLE
Case sensitivity table names Windows vs Linux

### ISSUE THREAD

**Issue by dvanderleij** [refactoring-ai/Machine-Learning#9]
`pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT processmetrics.authorOwnership, processmetrics.bugFixCount, processmetrics.qtyMajorAuthors, processmetrics.qtyMinorAuthors, processmetrics.qtyOfAuthors, processmetrics.qtyOfCommits, processmetrics.refactoringsInvolved FROM stablecommit INNER JOIN commitmetadata ON stablecommit.commitmetadata_id = commitmetadata.id INNER JOIN processmetrics ON stablecommit.processmetrics_id = processmetrics.id WHERE stablecommit.level = 0 AND stablecommit.project_id in (select id from project where datasetName = "github")  order by commitmetadata.commitDate': 1146 (42S02): Table 'refactoringdb.commitmetadata' doesn't exist`

I think this is caused by case sensitivity between windows and Linux.
https://stackoverflow.com/questions/6134006/are-table-names-in-mysql-case-sensitive?rq=1
On Windows tables are case insensitive as seen by the above post. However in Linux they are not causing the python scripts to fail since the tables are camel cased while in the python program they are all lower case

**Comment by jan-gerling** [comment]
I will fix this.
